---
name: activemodel
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: c560bb18418e07a709f80954db2e2d975bbd6e14
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
